defaults:
  - default.yaml

# ==============================
# Input shape: (3, 1024, 1024)
# Flops: 135.54 GFLOPs
# Params: 3.01 M
# ==============================

_target_:  trainers.modules.BaseChange.BaseChangeLite
example_input_array: [1, 3, 256, 256]
HPARAMS_LOG: True
CKPT: null
Config:
  MODEL: 
    type: BIT
    in_ch: 3
    out_ch: 2
    backbone: 'resnet18'
    n_stages: 4
    use_tokenizer: True
    token_len: 4
    pool_mode: 'max'
    pool_size: 2
    enc_with_pos: True
    enc_depth: 1
    enc_head_dim: 64
    dec_with_softmax: True
    dec_depth: 8
    dec_head_dim: 64

# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃        Test metric        ┃       DataLoader 0        ┃
# ┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
# │        test/.F1_1         │    0.8904182770652735     0.8924986865405043│
# │         test/.acc         │    0.9890534058213225      0.9891646280884734 │
# │        test/.iou_1        │    0.8024811206368757      0.8058670299704114│
# │     test/.precision_1     │    0.9085249372354841     0.9022765734625634│
# │      test/.recall_1       │    0.8730193506190209     0.8829305683852957│
# └───────────────────────────┴───────────────────────────┘