_target_: trainers.datamodule.cdd.generalcd.GeneralCDDataModule

train_dataset:
  type: 'GeneralCDDataset'
  root: /workspace/data/LEVIR_256
  split: 'train'
  load_from_txt: True
  transforms:
    type: CDDSequenceTransform
    img_size: null
    with_random_hflip: True
    with_random_vflip: True
    with_random_rot: True
    with_perspective: true
val_dataset:
  type: 'GeneralCDDataset'
  root:  /workspace/data/LEVIR_1024
  split: 'val'
  load_from_txt: False
  transforms:
    type: CDDSequenceTransform #CDDSequenceTransform CDDataAugmentation
    img_size: null

test_dataset:
  type: 'GeneralCDDataset'
  root:  /workspace/data/LEVIR_1024
  split: 'test'
  load_from_txt: False
  transforms:
    type: CDDSequenceTransform
    img_size: null

batch_size: 16

val_batch_size: 4
num_workers: 2
pin_memory: True